
on:
  push:
    branches:
      -  main


jobs:
  python-run:
    runs-on: ubuntu-latest
    steps:
    -  uses: actions/checkout@v7
    -  uses: actions/setup-python@v7

       with:
         python-version: '3.13'
    -  run: echo 'ls -la'
    -  run:  python app.py 
